include:
  - ./traefik/docker-compose.yml
  - ./pret-a-pousser/docker-compose.yml
  - ./bento-pdf/docker-compose.yml
  - ./vert/docker-compose.yml
  - ./portal/docker-compose.yml
  - ./sso/docker-compose.yml

#networks:
  #proxy:
    #name: proxy

networks:
  proxy:
    external: true
  docker-control:
    internal: true

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:0.1.2
    restart: unless-stopped
    environment:
      CONTAINERS: "1"
      EVENTS: "1"
      NETWORKS: "1"
      PING: "1"
      VERSION: "1"
      POST: "0"
    networks:
      - docker-control
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

secrets:
  keycloak_db_password:
    file: ./sso/secrets/keycloak_db_password
  keycloak_admin_password:
    file: ./sso/secrets/keycloak_admin_password
  oauth2_proxy_client_secret:
    file: ./sso/secrets/oauth2_proxy_client_secret
  oauth2_proxy_cookie_secret:
    file: ./sso/secrets/oauth2_proxy_cookie_secret