set shell := ["bash", "-cu"]

tf_dir := "./iac"
tf_vars := "../config/terraform.tfvars"

# List of available haos commands
default:
	@just --list

[private]
tf command:
	@if command -v tofu >/dev/null 2>&1; then \
	  tf_bin="$(command -v tofu)"; \
	elif command -v terraform >/dev/null 2>&1; then \
	  tf_bin="$(command -v terraform)"; \
	elif [[ -x /snap/bin/tofu ]]; then \
	  tf_bin="/snap/bin/tofu"; \
	else \
	  echo "OpenTofu/Terraform introuvable (installe tofu ou terraform)"; \
	  exit 1; \
	fi; \
	if [[ "$(id -u)" -ne 0 ]]; then \
	  sudo "$tf_bin" -chdir={{tf_dir}} {{command}}; \
	else \
	  "$tf_bin" -chdir={{tf_dir}} {{command}}; \
	fi

# Initialize the Terraform configuration
init:
	@just tf init

# Show the Terraform plan
plan:
	@just tf "plan -var-file={{tf_vars}}"

# Apply the Terraform configuration
apply:
	@just tf "apply -var-file={{tf_vars}}"

# Destroy the Terraform-managed infrastructure
destroy:
	@just tf "destroy -var-file={{tf_vars}}"

# Show the Terraform outputs
output:
	@just tf output