# docker-compose.yml
services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    expose:
      - '8080'
    restart: unless-stopped
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bento-pdf.rule=Host(`${BENTO_PDF_WEB_HOST:-bento-pdf.doudou.house}`)"
      - "traefik.http.routers.bento-pdf.entrypoints=websecure"
      - "traefik.http.routers.bento-pdf.tls.certresolver=leresolver"
      - "traefik.http.routers.bento-pdf.middlewares=auth"
      - "doudou.portal.routers.bento-pdf.description=PDF tools"
      - "traefik.http.services.bento-pdf.loadbalancer.server.port=8080"
      # echo -n "user:$(openssl passwd -apr1 'password') >> .htpasswd"

networks:
  proxy:
    external: true