services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    expose:
      - '80'
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vert.rule=Host(`${VERT_WEB_HOST:-vert.doudou.house}`)"
      - "traefik.http.routers.vert.entrypoints=websecure"
      - "traefik.http.routers.vert.tls.certresolver=leresolver"
      - "traefik.http.routers.vert.middlewares=auth"
      - "doudou.portal.routers.vert.description=File conversion"
      - "traefik.http.services.vert.loadbalancer.server.port=80"

networks:
  proxy:
    external: true