set shell := ["bash", "-cu"]

default:
	@just --list

install:
	sudo ./cockpit-machines.sh install

revert:
	sudo ./cockpit-machines.sh revert

status:
	sudo ./cockpit-machines.sh status

check:
	sudo ./cockpit-machines.sh check

doctor:
	sudo ./cockpit-machines.sh doctor

logs:
	sudo ./cockpit-machines.sh logs

url:
	./cockpit-machines.sh url